package com.example.playersquiz.remote.models

data class RootMetadataRemoteModel (
    val siteId: Long? = null,
    val supportPhoneNumber: RootMetadataSupportPhoneNumberRemoteModel? = null,
    val TPID: Long? = null,
    val EAPID: Long? = null,
    val gdprEnabled: Boolean? = null,
    val flightsEnabled: Boolean? = null,
    val packagesEnabled: Boolean? = null,
    val packagesHSRIncludesHeaderEnabled: Boolean? = null,
    val removeAvailabilityMessageEnabled: Boolean? = null,
    val showStrikeThroughPriceDetails: Boolean? = null,
    val showETPPreauthorizationsMessage: Boolean? = null,
    val carsEnabled: Boolean? = null,
    val lxEnabled: Boolean? = null,
    val swpEnabledHotels: Boolean? = null,
    val earnMessageEnabledHotels: Boolean? = null,
    val carsWebViewEnabled: Boolean? = null,
    val url: String? = null,
    val countryCode: String? = null,
    val supportedLocales: List<RootMetadataSupportedLocaleRemoteModel>? = null,
    val branding: String? = null,
    val deepLinkDateFormat: String? = null,
    val pointOfSaleId: Long? = null,
    val shouldDisplayAveragePrices: Boolean? = null,
    val automaticallyMappedLocales: List<String>? = null,
    val shouldShowRewards: Boolean? = null,
    val supportsVipAccess: Boolean? = null,
    val marketingOptIn: String? = null,
    val hotMIPSavingsPercentage: String? = null,
    val vrboTermsAndConditionsURL: String? = null,
    val cookiePolicyURLString: String? = null,
    val enrollInLoyalty: Boolean? = null
)